set -g default-terminal "tmux-256color"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
setw -g mode-keys vi
unbind C-b
set -g prefix `
bind ` send-prefix

bind [ split-window -h
bind ] split-window -v
unbind %
unbind '"'
set -sg escape-time 0
bind r source-file ~/.tmux.conf \; display "reloaded"
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g status-style 'bg=colour236 fg=colour59'
set -g status-left ''
set -g status-right ''
set -g window-status-current-style 'fg=white'
set -g window-status-style 'fg=colour59'
set -g pane-border-style 'fg=colour236'
set -g pane-active-border-style 'fg=colour67'
set -g message-style 'bg=colour236 fg=white'
set -g message-command-style 'bg=colour236 fg=white'
set -g mode-style 'bg=colour67 fg=white'
set -g copy-mode-match-style 'bg=colour236 fg=colour102'
set -g copy-mode-current-match-style 'bg=colour67 fg=white'
